solid = false;
mask_index = spr_no_mask;
hspeed = 0;
vspeed = 0;
var fishingSpot = instance_nearest(x, y, obj_fishing_spot);
x = fishingSpot.x;
y = (fishingSpot.y)-6;
sprite_index = spr_plr_fishing;
image_xscale = fishingSpot.facingDirection;