// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_animal_parent
global.__objectDepths[1] = -101; // obj_cow
global.__objectDepths[2] = -101; // obj_chicken
global.__objectDepths[3] = 0; // obj_block_grass
global.__objectDepths[4] = -100; // obj_mount_horse
global.__objectDepths[5] = 0; // obj_block_parent
global.__objectDepths[6] = 0; // obj_block_stone
global.__objectDepths[7] = 0; // obj_block_stonebrick
global.__objectDepths[8] = -1; // obj_block_stonebrick_bg
global.__objectDepths[9] = -1; // obj_heikko
global.__objectDepths[10] = -103; // obj_block_water
global.__objectDepths[11] = -80; // obj_maa
global.__objectDepths[12] = -87; // obj_secret_stonewall
global.__objectDepths[13] = 0; // obj_solidify_parent
global.__objectDepths[14] = -70; // obj_dec_pennant
global.__objectDepths[15] = -70; // obj_dec_wall_flag
global.__objectDepths[16] = -100; // obj_dec_castle_gate
global.__objectDepths[17] = -50; // obj_dec_window
global.__objectDepths[18] = -100; // obj_dec_chair
global.__objectDepths[19] = -100; // obj_dec_table
global.__objectDepths[20] = -100; // obj_dec_cup
global.__objectDepths[21] = -100; // obj_dec_chair_parent
global.__objectDepths[22] = -100; // obj_dec_knight_statue
global.__objectDepths[23] = -90; // obj_dec_candlestick
global.__objectDepths[24] = -100; // obj_dec_stairs
global.__objectDepths[25] = -82; // obj_blacksmith
global.__objectDepths[26] = -81; // obj_blacksmith_floor
global.__objectDepths[27] = -81; // obj_blacksmith_roof
global.__objectDepths[28] = -80; // obj_blacksmith_shop
global.__objectDepths[29] = -81; // obj_blacksmith_wall
global.__objectDepths[30] = -100; // obj_cave_bridge
global.__objectDepths[31] = -100; // obj_cave_bridge_broken
global.__objectDepths[32] = -100; // obj_cave_bridge_left
global.__objectDepths[33] = -100; // obj_cave_bridge_right
global.__objectDepths[34] = -82; // obj_cave_door
global.__objectDepths[35] = -82; // obj_door
global.__objectDepths[36] = -82; // obj_door_locked
global.__objectDepths[37] = -100; // obj_platform
global.__objectDepths[38] = -101; // obj_feather
global.__objectDepths[39] = -200; // obj_salmon
global.__objectDepths[40] = -200; // obj_tuna
global.__objectDepths[41] = -102; // obj_fishing_bobber
global.__objectDepths[42] = -82; // obj_fishing_spot
global.__objectDepths[43] = -101; // obj_fishing_vein
global.__objectDepths[44] = -85; // obj_barbarea_vulgaris
global.__objectDepths[45] = -85; // obj_celandine
global.__objectDepths[46] = -85; // obj_camomile
global.__objectDepths[47] = -85; // obj_lambsquarter
global.__objectDepths[48] = -85; // obj_nettle
global.__objectDepths[49] = -85; // obj_plantain
global.__objectDepths[50] = -85; // obj_sheeps_sorrel
global.__objectDepths[51] = -85; // obj_water_flask
global.__objectDepths[52] = 0; // obj_ingredient_parent
global.__objectDepths[53] = -98; // obj_coin
global.__objectDepths[54] = -85; // obj_chest
global.__objectDepths[55] = -5003; // obj_coin_collected
global.__objectDepths[56] = -98; // obj_coin_dropped
global.__objectDepths[57] = -85; // obj_dropped_item
global.__objectDepths[58] = -81; // obj_medicpack
global.__objectDepths[59] = -5003; // obj_potion_collected
global.__objectDepths[60] = -82; // obj_source_iron_ore
global.__objectDepths[61] = -85; // obj_healing_potion
global.__objectDepths[62] = -82; // obj_source_oak_tree
global.__objectDepths[63] = -82; // spr_source_spruce_tree
global.__objectDepths[64] = 0; // obj_source_tree_parent
global.__objectDepths[65] = -100; // obj_alchemy_station
global.__objectDepths[66] = -100; // obj_anvil
global.__objectDepths[67] = 0; // obj_crafting_station_parent
global.__objectDepths[68] = -100; // obj_forge
global.__objectDepths[69] = -100; // obj_workbench
global.__objectDepths[70] = -100; // obj_stove
global.__objectDepths[71] = -85; // obj_wood_billet
global.__objectDepths[72] = -85; // obj_wooden_handle
global.__objectDepths[73] = 0; // obj_workbench_material_parent
global.__objectDepths[74] = -103; // obj_arrow_effect
global.__objectDepths[75] = -83; // obj_wood_dust
global.__objectDepths[76] = -98; // obj_wood_hit
global.__objectDepths[77] = -99; // obj_dust
global.__objectDepths[78] = -98; // obj_mining_hit
global.__objectDepths[79] = -83; // obj_mining_dust
global.__objectDepths[80] = -300; // obj_blood
global.__objectDepths[81] = -83; // obj_leaf
global.__objectDepths[82] = -100; // obj_lever_signal
global.__objectDepths[83] = -81; // obj_heal
global.__objectDepths[84] = -102; // obj_body
global.__objectDepths[85] = -100; // obj_
global.__objectDepths[86] = -99; // obj_archer
global.__objectDepths[87] = -100; // obj_archer_bow
global.__objectDepths[88] = -83; // obj_cannon_left
global.__objectDepths[89] = -100; // obj_bat
global.__objectDepths[90] = -83; // obj_cannon_right
global.__objectDepths[91] = -100; // obj_enemy
global.__objectDepths[92] = 0; // obj_enemy_parent
global.__objectDepths[93] = -100; // obj_enemy_hit
global.__objectDepths[94] = -80; // obj_enemy2
global.__objectDepths[95] = -100; // obj_shadow
global.__objectDepths[96] = -100; // obj_rat
global.__objectDepths[97] = -79; // obj_enemy_arrow
global.__objectDepths[98] = 0; // obj_enemy_attack_parent
global.__objectDepths[99] = -100; // obj_enemy_shadow_ball
global.__objectDepths[100] = -82; // obj_home_farmland
global.__objectDepths[101] = -82; // obj_home_blacksmith
global.__objectDepths[102] = -83; // obj_home_purchasable
global.__objectDepths[103] = -5200; // obj_crafted_item
global.__objectDepths[104] = 0; // obj_home_village_controller
global.__objectDepths[105] = -5000; // obj_crafting_bg_controller
global.__objectDepths[106] = -5100; // obj_crafting_close_button
global.__objectDepths[107] = -5100; // obj_crafting_slot_2
global.__objectDepths[108] = -5100; // obj_crafting_slot_1
global.__objectDepths[109] = -5100; // obj_crafting_slot_3
global.__objectDepths[110] = -5100; // obj_crafting_slot_4
global.__objectDepths[111] = 0; // obj_crafting_slot_parent
global.__objectDepths[112] = -5002; // obj_crafting_controller
global.__objectDepths[113] = -4100; // obj_dialog_bg_controller
global.__objectDepths[114] = -5000; // obj_dialog_controller
global.__objectDepths[115] = -5001; // obj_dialog_option
global.__objectDepths[116] = -1000; // obj_building
global.__objectDepths[117] = -5002; // obj_skill_A
global.__objectDepths[118] = -5002; // obj_skill_Q
global.__objectDepths[119] = -5002; // obj_skill_W
global.__objectDepths[120] = 0; // obj_inv_button_parent
global.__objectDepths[121] = -5003; // obj_inv_close_button
global.__objectDepths[122] = -5003; // obj_inv_backpack_button
global.__objectDepths[123] = -5003; // obj_inv_equipments_button
global.__objectDepths[124] = -5003; // obj_inv_save_exit_button
global.__objectDepths[125] = -5003; // obj_inv_skill_tree_button
global.__objectDepths[126] = -5003; // obj_inv_stats_button
global.__objectDepths[127] = -5002; // obj_inventory_controller
global.__objectDepths[128] = -5100; // obj_skill_tree_skill
global.__objectDepths[129] = -2; // obj_menu_achievements
global.__objectDepths[130] = 0; // obj_menu_button_parent
global.__objectDepths[131] = -2; // obj_menu_options
global.__objectDepths[132] = -1; // obj_menu_orb_of_dysforia
global.__objectDepths[133] = -1; // obj_menu_orb_of_euphoria
global.__objectDepths[134] = 0; // obj_menu_orb_parent
global.__objectDepths[135] = -2; // obj_menu_play
global.__objectDepths[136] = -2; // obj_menu_load_game
global.__objectDepths[137] = -2; // obj_menu_delete
global.__objectDepths[138] = -2; // obj_menu_quit
global.__objectDepths[139] = -2; // obj_menu_back
global.__objectDepths[140] = -5100; // obj_search_box
global.__objectDepths[141] = -2; // obj_menu_saved_game
global.__objectDepths[142] = -5005; // obj_button_confirm
global.__objectDepths[143] = -5004; // obj_button_decrease
global.__objectDepths[144] = -5005; // obj_button_increase
global.__objectDepths[145] = -4000; // obj_darkness
global.__objectDepths[146] = -5100; // obj_exp_counter
global.__objectDepths[147] = 0; // obj_first_loading
global.__objectDepths[148] = -5001; // obj_hotbar_bg_controller
global.__objectDepths[149] = -4002; // obj_money_target
global.__objectDepths[150] = -5200; // obj_listed_item
global.__objectDepths[151] = -11000; // obj_mouse
global.__objectDepths[152] = -1001; // obj_plr_pointer
global.__objectDepths[153] = -4002; // obj_potion_target
global.__objectDepths[154] = -5004; // obj_quest_controller
global.__objectDepths[155] = -5000; // obj_shop_bg_controller
global.__objectDepths[156] = -6000; // obj_screen_controller
global.__objectDepths[157] = -5002; // obj_shop_controller
global.__objectDepths[158] = -5100; // obj_lives
global.__objectDepths[159] = -5100; // obj_mana
global.__objectDepths[160] = -5100; // obj_stamina
global.__objectDepths[161] = -10002; // obj_map_mountain
global.__objectDepths[162] = -10001; // obj_map_cargo_cart
global.__objectDepths[163] = -5100; // obj_world_map_controller
global.__objectDepths[164] = -10002; // obj_map_forest
global.__objectDepths[165] = -10000; // obj_map_castle
global.__objectDepths[166] = -86; // obj_barrel
global.__objectDepths[167] = 0; // obj_map_grid
global.__objectDepths[168] = -2000; // obj_blocker5
global.__objectDepths[169] = -86; // obj_crate
global.__objectDepths[170] = -86; // obj_crate_0001
global.__objectDepths[171] = -103; // obj_crate_0002
global.__objectDepths[172] = -82; // obj_furnace
global.__objectDepths[173] = -82; // obj_desk
global.__objectDepths[174] = -85; // obj_gold_bar
global.__objectDepths[175] = -102; // obj_grave
global.__objectDepths[176] = -85; // obj_iron_bar
global.__objectDepths[177] = -79; // obj_ladder
global.__objectDepths[178] = -100; // obj_lever
global.__objectDepths[179] = -82; // obj_shelf
global.__objectDepths[180] = -101; // obj_torch
global.__objectDepths[181] = -81; // obj_sign
global.__objectDepths[182] = -82; // obj_weaponrack
global.__objectDepths[183] = -83; // obj_blacksmith_shoper
global.__objectDepths[184] = -101; // obj_merchant
global.__objectDepths[185] = -101; // obj_NPC
global.__objectDepths[186] = 0; // obj_NPC_parent
global.__objectDepths[187] = -100; // obj_aim
global.__objectDepths[188] = -100; // obj_cargon_cart_wheel
global.__objectDepths[189] = -1000; // obj_compass
global.__objectDepths[190] = -100; // obj_cycle
global.__objectDepths[191] = 0; // obj_enemy_turn_left
global.__objectDepths[192] = 0; // obj_enemy_turn_right
global.__objectDepths[193] = -1000; // obj_goal
global.__objectDepths[194] = -1000; // obj_pause
global.__objectDepths[195] = -102; // obj_pet
global.__objectDepths[196] = -100; // obj_pet_ammo
global.__objectDepths[197] = 0; // obj_plr_attack_parent
global.__objectDepths[198] = -103; // obj_plr_shield
global.__objectDepths[199] = -500; // obj_use
global.__objectDepths[200] = -79; // obj_plr_arrow
global.__objectDepths[201] = -500; // obj_plr_slice
global.__objectDepths[202] = -102; // obj_player
global.__objectDepths[203] = -100; // obj_plr_aim
global.__objectDepths[204] = -103; // obj_plr_bow
global.__objectDepths[205] = -101; // obj_plr_hitbox
global.__objectDepths[206] = -100; // obj_spawner
global.__objectDepths[207] = -85; // obj_tool_knife
global.__objectDepths[208] = -85; // obj_tool_saw
global.__objectDepths[209] = 0; // obj_tool_parent
global.__objectDepths[210] = -30; // obj_spikes
global.__objectDepths[211] = 0; // obj_world
global.__objectDepths[212] = -100; // obj___ammo
global.__objectDepths[213] = -81; // obj_arrow1
global.__objectDepths[214] = -82; // obj_cannonball
global.__objectDepths[215] = -85; // obj_broken_helmet
global.__objectDepths[216] = -85; // obj_arrow_pouch
global.__objectDepths[217] = -85; // obj_bow
global.__objectDepths[218] = 0; // obj_equipment_parent


global.__objectNames[0] = "obj_animal_parent";
global.__objectNames[1] = "obj_cow";
global.__objectNames[2] = "obj_chicken";
global.__objectNames[3] = "obj_block_grass";
global.__objectNames[4] = "obj_mount_horse";
global.__objectNames[5] = "obj_block_parent";
global.__objectNames[6] = "obj_block_stone";
global.__objectNames[7] = "obj_block_stonebrick";
global.__objectNames[8] = "obj_block_stonebrick_bg";
global.__objectNames[9] = "obj_heikko";
global.__objectNames[10] = "obj_block_water";
global.__objectNames[11] = "obj_maa";
global.__objectNames[12] = "obj_secret_stonewall";
global.__objectNames[13] = "obj_solidify_parent";
global.__objectNames[14] = "obj_dec_pennant";
global.__objectNames[15] = "obj_dec_wall_flag";
global.__objectNames[16] = "obj_dec_castle_gate";
global.__objectNames[17] = "obj_dec_window";
global.__objectNames[18] = "obj_dec_chair";
global.__objectNames[19] = "obj_dec_table";
global.__objectNames[20] = "obj_dec_cup";
global.__objectNames[21] = "obj_dec_chair_parent";
global.__objectNames[22] = "obj_dec_knight_statue";
global.__objectNames[23] = "obj_dec_candlestick";
global.__objectNames[24] = "obj_dec_stairs";
global.__objectNames[25] = "obj_blacksmith";
global.__objectNames[26] = "obj_blacksmith_floor";
global.__objectNames[27] = "obj_blacksmith_roof";
global.__objectNames[28] = "obj_blacksmith_shop";
global.__objectNames[29] = "obj_blacksmith_wall";
global.__objectNames[30] = "obj_cave_bridge";
global.__objectNames[31] = "obj_cave_bridge_broken";
global.__objectNames[32] = "obj_cave_bridge_left";
global.__objectNames[33] = "obj_cave_bridge_right";
global.__objectNames[34] = "obj_cave_door";
global.__objectNames[35] = "obj_door";
global.__objectNames[36] = "obj_door_locked";
global.__objectNames[37] = "obj_platform";
global.__objectNames[38] = "obj_feather";
global.__objectNames[39] = "obj_salmon";
global.__objectNames[40] = "obj_tuna";
global.__objectNames[41] = "obj_fishing_bobber";
global.__objectNames[42] = "obj_fishing_spot";
global.__objectNames[43] = "obj_fishing_vein";
global.__objectNames[44] = "obj_barbarea_vulgaris";
global.__objectNames[45] = "obj_celandine";
global.__objectNames[46] = "obj_camomile";
global.__objectNames[47] = "obj_lambsquarter";
global.__objectNames[48] = "obj_nettle";
global.__objectNames[49] = "obj_plantain";
global.__objectNames[50] = "obj_sheeps_sorrel";
global.__objectNames[51] = "obj_water_flask";
global.__objectNames[52] = "obj_ingredient_parent";
global.__objectNames[53] = "obj_coin";
global.__objectNames[54] = "obj_chest";
global.__objectNames[55] = "obj_coin_collected";
global.__objectNames[56] = "obj_coin_dropped";
global.__objectNames[57] = "obj_dropped_item";
global.__objectNames[58] = "obj_medicpack";
global.__objectNames[59] = "obj_potion_collected";
global.__objectNames[60] = "obj_source_iron_ore";
global.__objectNames[61] = "obj_healing_potion";
global.__objectNames[62] = "obj_source_oak_tree";
global.__objectNames[63] = "spr_source_spruce_tree";
global.__objectNames[64] = "obj_source_tree_parent";
global.__objectNames[65] = "obj_alchemy_station";
global.__objectNames[66] = "obj_anvil";
global.__objectNames[67] = "obj_crafting_station_parent";
global.__objectNames[68] = "obj_forge";
global.__objectNames[69] = "obj_workbench";
global.__objectNames[70] = "obj_stove";
global.__objectNames[71] = "obj_wood_billet";
global.__objectNames[72] = "obj_wooden_handle";
global.__objectNames[73] = "obj_workbench_material_parent";
global.__objectNames[74] = "obj_arrow_effect";
global.__objectNames[75] = "obj_wood_dust";
global.__objectNames[76] = "obj_wood_hit";
global.__objectNames[77] = "obj_dust";
global.__objectNames[78] = "obj_mining_hit";
global.__objectNames[79] = "obj_mining_dust";
global.__objectNames[80] = "obj_blood";
global.__objectNames[81] = "obj_leaf";
global.__objectNames[82] = "obj_lever_signal";
global.__objectNames[83] = "obj_heal";
global.__objectNames[84] = "obj_body";
global.__objectNames[85] = "obj_";
global.__objectNames[86] = "obj_archer";
global.__objectNames[87] = "obj_archer_bow";
global.__objectNames[88] = "obj_cannon_left";
global.__objectNames[89] = "obj_bat";
global.__objectNames[90] = "obj_cannon_right";
global.__objectNames[91] = "obj_enemy";
global.__objectNames[92] = "obj_enemy_parent";
global.__objectNames[93] = "obj_enemy_hit";
global.__objectNames[94] = "obj_enemy2";
global.__objectNames[95] = "obj_shadow";
global.__objectNames[96] = "obj_rat";
global.__objectNames[97] = "obj_enemy_arrow";
global.__objectNames[98] = "obj_enemy_attack_parent";
global.__objectNames[99] = "obj_enemy_shadow_ball";
global.__objectNames[100] = "obj_home_farmland";
global.__objectNames[101] = "obj_home_blacksmith";
global.__objectNames[102] = "obj_home_purchasable";
global.__objectNames[103] = "obj_crafted_item";
global.__objectNames[104] = "obj_home_village_controller";
global.__objectNames[105] = "obj_crafting_bg_controller";
global.__objectNames[106] = "obj_crafting_close_button";
global.__objectNames[107] = "obj_crafting_slot_2";
global.__objectNames[108] = "obj_crafting_slot_1";
global.__objectNames[109] = "obj_crafting_slot_3";
global.__objectNames[110] = "obj_crafting_slot_4";
global.__objectNames[111] = "obj_crafting_slot_parent";
global.__objectNames[112] = "obj_crafting_controller";
global.__objectNames[113] = "obj_dialog_bg_controller";
global.__objectNames[114] = "obj_dialog_controller";
global.__objectNames[115] = "obj_dialog_option";
global.__objectNames[116] = "obj_building";
global.__objectNames[117] = "obj_skill_A";
global.__objectNames[118] = "obj_skill_Q";
global.__objectNames[119] = "obj_skill_W";
global.__objectNames[120] = "obj_inv_button_parent";
global.__objectNames[121] = "obj_inv_close_button";
global.__objectNames[122] = "obj_inv_backpack_button";
global.__objectNames[123] = "obj_inv_equipments_button";
global.__objectNames[124] = "obj_inv_save_exit_button";
global.__objectNames[125] = "obj_inv_skill_tree_button";
global.__objectNames[126] = "obj_inv_stats_button";
global.__objectNames[127] = "obj_inventory_controller";
global.__objectNames[128] = "obj_skill_tree_skill";
global.__objectNames[129] = "obj_menu_achievements";
global.__objectNames[130] = "obj_menu_button_parent";
global.__objectNames[131] = "obj_menu_options";
global.__objectNames[132] = "obj_menu_orb_of_dysforia";
global.__objectNames[133] = "obj_menu_orb_of_euphoria";
global.__objectNames[134] = "obj_menu_orb_parent";
global.__objectNames[135] = "obj_menu_play";
global.__objectNames[136] = "obj_menu_load_game";
global.__objectNames[137] = "obj_menu_delete";
global.__objectNames[138] = "obj_menu_quit";
global.__objectNames[139] = "obj_menu_back";
global.__objectNames[140] = "obj_search_box";
global.__objectNames[141] = "obj_menu_saved_game";
global.__objectNames[142] = "obj_button_confirm";
global.__objectNames[143] = "obj_button_decrease";
global.__objectNames[144] = "obj_button_increase";
global.__objectNames[145] = "obj_darkness";
global.__objectNames[146] = "obj_exp_counter";
global.__objectNames[147] = "obj_first_loading";
global.__objectNames[148] = "obj_hotbar_bg_controller";
global.__objectNames[149] = "obj_money_target";
global.__objectNames[150] = "obj_listed_item";
global.__objectNames[151] = "obj_mouse";
global.__objectNames[152] = "obj_plr_pointer";
global.__objectNames[153] = "obj_potion_target";
global.__objectNames[154] = "obj_quest_controller";
global.__objectNames[155] = "obj_shop_bg_controller";
global.__objectNames[156] = "obj_screen_controller";
global.__objectNames[157] = "obj_shop_controller";
global.__objectNames[158] = "obj_lives";
global.__objectNames[159] = "obj_mana";
global.__objectNames[160] = "obj_stamina";
global.__objectNames[161] = "obj_map_mountain";
global.__objectNames[162] = "obj_map_cargo_cart";
global.__objectNames[163] = "obj_world_map_controller";
global.__objectNames[164] = "obj_map_forest";
global.__objectNames[165] = "obj_map_castle";
global.__objectNames[166] = "obj_barrel";
global.__objectNames[167] = "obj_map_grid";
global.__objectNames[168] = "obj_blocker5";
global.__objectNames[169] = "obj_crate";
global.__objectNames[170] = "obj_crate_0001";
global.__objectNames[171] = "obj_crate_0002";
global.__objectNames[172] = "obj_furnace";
global.__objectNames[173] = "obj_desk";
global.__objectNames[174] = "obj_gold_bar";
global.__objectNames[175] = "obj_grave";
global.__objectNames[176] = "obj_iron_bar";
global.__objectNames[177] = "obj_ladder";
global.__objectNames[178] = "obj_lever";
global.__objectNames[179] = "obj_shelf";
global.__objectNames[180] = "obj_torch";
global.__objectNames[181] = "obj_sign";
global.__objectNames[182] = "obj_weaponrack";
global.__objectNames[183] = "obj_blacksmith_shoper";
global.__objectNames[184] = "obj_merchant";
global.__objectNames[185] = "obj_NPC";
global.__objectNames[186] = "obj_NPC_parent";
global.__objectNames[187] = "obj_aim";
global.__objectNames[188] = "obj_cargon_cart_wheel";
global.__objectNames[189] = "obj_compass";
global.__objectNames[190] = "obj_cycle";
global.__objectNames[191] = "obj_enemy_turn_left";
global.__objectNames[192] = "obj_enemy_turn_right";
global.__objectNames[193] = "obj_goal";
global.__objectNames[194] = "obj_pause";
global.__objectNames[195] = "obj_pet";
global.__objectNames[196] = "obj_pet_ammo";
global.__objectNames[197] = "obj_plr_attack_parent";
global.__objectNames[198] = "obj_plr_shield";
global.__objectNames[199] = "obj_use";
global.__objectNames[200] = "obj_plr_arrow";
global.__objectNames[201] = "obj_plr_slice";
global.__objectNames[202] = "obj_player";
global.__objectNames[203] = "obj_plr_aim";
global.__objectNames[204] = "obj_plr_bow";
global.__objectNames[205] = "obj_plr_hitbox";
global.__objectNames[206] = "obj_spawner";
global.__objectNames[207] = "obj_tool_knife";
global.__objectNames[208] = "obj_tool_saw";
global.__objectNames[209] = "obj_tool_parent";
global.__objectNames[210] = "obj_spikes";
global.__objectNames[211] = "obj_world";
global.__objectNames[212] = "obj___ammo";
global.__objectNames[213] = "obj_arrow1";
global.__objectNames[214] = "obj_cannonball";
global.__objectNames[215] = "obj_broken_helmet";
global.__objectNames[216] = "obj_arrow_pouch";
global.__objectNames[217] = "obj_bow";
global.__objectNames[218] = "obj_equipment_parent";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for